asignado(6,musica,alonso,mie,1,a).
asignado(6,mate,daleana,jue,2,a).
asignado(6,mate,daleana,vie,1,a).
asignado(6,mate,daleana,vie,3,a).
asignado(6,mate,daleana,mar,2,b).
asignado(6,mate,daleana,mar,3,b).
asignado(6,mate,daleana,jue,3,b).
asignado(6,mate,daleana,jue,4,b).
asignado(6,mate,daleana,vie,1,b).
asignado(6,ingles,melissa,mie,2,a).
asignado(6,ingles,melissa,mie,3,a).
asignado(6,ingles,melissa,jue,1,a).
asignado(6,ingles,melissa,jue,3,a).
asignado(6,ingles,melissa,jue,4,a).
asignado(6,ingles,melissa,vie,4,a).
asignado(6,ingles,melissa,mar,4,b).
asignado(6,ingles,melissa,mie,4,b).
asignado(6,ingles,melissa,vie,4,b).
asignado(6,infor,jonathan,lun,2,b).
asignado(6,infor,jonathan,vie,3,b).
asignado(6,frances,angie,lun,2,a).
asignado(6,frances,angie,mar,3,a).
asignado(6,etica,alisson,mar,1,b).
asignado(6,estsoc,daleana,lun,3,a).
asignado(6,estsoc,daleana,mar,4,a).
asignado(6,estsoc,daleana,lun,1,b).
asignado(6,estsoc,daleana,lun,3,b).
asignado(6,espannol,daleana,lun,1,a).
asignado(6,espannol,daleana,lun,4,a).
asignado(6,espannol,daleana,mar,1,a).
asignado(6,espannol,daleana,lun,4,b).
asignado(6,espannol,daleana,jue,1,b).
asignado(6,edfis,mpaula,mar,2,a).
asignado(6,edfis,mpaula,vie,2,a).
asignado(6,ciencias,daleana,mie,4,a).
asignado(6,ciencias,daleana,mie,1,b).
asignado(6,ciencias,daleana,mie,2,b).
asignado(6,ciencias,daleana,mie,3,b).
asignado(6,ciencias,daleana,jue,2,b).
asignado(6,ciencias,daleana,vie,2,b).
asignado(5,musica,alonso,mie,3,a).
asignado(5,mate,mayela,lun,3,a).
asignado(5,mate,mayela,mar,4,a).
asignado(5,mate,mayela,mie,1,a).
asignado(5,mate,mayela,jue,1,a).
asignado(5,mate,mayela,vie,3,a).
asignado(5,mate,mayela,jue,1,b).
asignado(5,mate,mayela,jue,4,b).
asignado(5,mate,mayela,vie,2,b).
asignado(5,ingles,gina,mie,2,a).
asignado(5,ingles,gina,mie,4,a).
asignado(5,ingles,gina,jue,2,a).
asignado(5,ingles,gina,jue,3,a).
asignado(5,ingles,gina,vie,2,a).
asignado(5,ingles,gina,lun,3,b).
asignado(5,ingles,gina,lun,4,b).
asignado(5,ingles,gina,mar,1,b).
asignado(5,ingles,gina,mar,3,b).
asignado(5,infor,jonathan,mie,1,b).
asignado(5,infor,jonathan,jue,2,b).
asignado(5,frances,angie,mar,2,b).
asignado(5,frances,angie,vie,3,b).
asignado(5,etica,alisson,mie,3,b).
asignado(5,estsoc,daleana,lun,1,a).
asignado(5,estsoc,daleana,mar,1,a).
asignado(5,estsoc,daleana,mar,3,a).
asignado(5,estsoc,daleana,lun,2,b).
asignado(5,estsoc,daleana,mar,4,b).
asignado(5,estsoc,daleana,mie,2,b).
asignado(5,espannol,daleana,lun,4,a).
asignado(5,espannol,daleana,vie,4,a).
asignado(5,espannol,daleana,lun,1,b).
asignado(5,espannol,daleana,mie,4,b).
asignado(5,espannol,daleana,vie,1,b).
asignado(5,edfis,mpaula,lun,2,a).
asignado(5,edfis,mpaula,mar,2,a).
asignado(5,ciencias,mayela,jue,4,a).
asignado(5,ciencias,mayela,vie,1,a).
asignado(5,ciencias,mayela,jue,3,b).
asignado(5,ciencias,mayela,vie,4,b).
asignado(4,musica,alonso,mie,4,b).
asignado(4,mate,mayela,mar,3,b).
asignado(4,mate,mayela,mar,4,b).
asignado(4,mate,mayela,jue,1,b).
asignado(4,mate,mayela,jue,4,b).
asignado(4,mate,mayela,vie,1,b).
asignado(4,mate,mayela,vie,2,b).
asignado(4,mate,mayela,vie,3,b).
asignado(4,mate,mayela,vie,4,b).
asignado(4,ingles,gina,mie,2,a).
asignado(4,ingles,gina,mie,3,a).
asignado(4,ingles,gina,vie,1,a).
asignado(4,ingles,gina,lun,2,b).
asignado(4,ingles,gina,lun,3,b).
asignado(4,ingles,gina,lun,4,b).
asignado(4,ingles,gina,mie,1,b).
asignado(4,ingles,gina,jue,2,b).
asignado(4,ingles,gina,jue,3,b).
asignado(4,infor,jonathan,mar,3,a).
asignado(4,infor,jonathan,mar,4,a).
asignado(4,etica,alisson,mar,2,a).
asignado(4,estsoc,mayela,lun,1,a).
asignado(4,estsoc,mayela,jue,1,a).
asignado(4,estsoc,mayela,jue,3,a).
asignado(4,estsoc,mayela,lun,1,b).
asignado(4,estsoc,mayela,mie,2,b).
asignado(4,espannol,mayela,lun,3,a).
asignado(4,espannol,mayela,lun,4,a).
asignado(4,espannol,mayela,mar,1,a).
asignado(4,espannol,mayela,mie,1,a).
asignado(4,espannol,mayela,mie,4,a).
asignado(4,espannol,mayela,mar,2,b).
asignado(4,edfis,mpaula,lun,2,a).
asignado(4,edfis,mpaula,mar,1,b).
asignado(4,ciencias,mayela,jue,2,a).
asignado(4,ciencias,mayela,jue,4,a).
asignado(4,ciencias,mayela,vie,3,a).
asignado(4,ciencias,mayela,vie,4,a).
asignado(3,musica,alonso,mie,4,b).
asignado(3,mate,audry,jue,1,a).
asignado(3,mate,audry,jue,1,b).
asignado(3,mate,audry,jue,3,b).
asignado(3,mate,audry,jue,4,b).
asignado(3,mate,audry,vie,1,b).
asignado(3,mate,audry,vie,2,b).
asignado(3,mate,audry,vie,3,b).
asignado(3,mate,audry,vie,4,b).
asignado(3,ingles,gina,mar,2,a).
asignado(3,ingles,gina,jue,3,a).
asignado(3,ingles,gina,jue,4,a).
asignado(3,ingles,gina,vie,4,a).
asignado(3,ingles,gina,lun,1,b).
asignado(3,ingles,gina,mar,1,b).
asignado(3,ingles,gina,mar,2,b).
asignado(3,ingles,gina,mar,3,b).
asignado(3,ingles,gina,mie,1,b).
asignado(3,ingles,gina,jue,2,b).
asignado(3,infor,jonathan,lun,3,a).
asignado(3,infor,jonathan,mie,3,b).
asignado(3,etica,mjose,mie,3,a).
asignado(3,estsoc,audry,mie,1,a).
asignado(3,estsoc,audry,jue,2,a).
asignado(3,estsoc,audry,lun,4,b).
asignado(3,estsoc,audry,mie,2,b).
asignado(3,espannol,audry,lun,1,a).
asignado(3,espannol,audry,lun,2,a).
asignado(3,espannol,audry,lun,4,a).
asignado(3,espannol,audry,mar,1,a).
asignado(3,espannol,audry,mar,3,a).
asignado(3,espannol,audry,mie,2,a).
asignado(3,espannol,audry,mie,4,a).
asignado(3,edfis,mpaula,mar,4,a).
asignado(3,edfis,mpaula,mar,4,b).
asignado(3,ciencias,audry,vie,1,a).
asignado(3,ciencias,audry,vie,3,a).
asignado(3,ciencias,audry,lun,2,b).
asignado(3,ciencias,audry,lun,3,b).
asignado(3,arte,mjose,vie,2,a).
asignado(2,musica,alonso,mie,4,b).
asignado(2,mate,mjose,mar,2,a).
asignado(2,mate,mjose,mar,3,a).
asignado(2,mate,mjose,mie,2,a).
asignado(2,mate,mjose,vie,1,a).
asignado(2,mate,mjose,vie,4,a).
asignado(2,mate,mjose,mar,4,b).
asignado(2,mate,mjose,mie,2,b).
asignado(2,mate,mjose,vie,2,b).
asignado(2,ingles,gina,lun,4,a).
asignado(2,ingles,gina,mar,1,a).
asignado(2,ingles,gina,mie,1,a).
asignado(2,ingles,gina,jue,4,a).
asignado(2,ingles,gina,vie,2,a).
asignado(2,ingles,gina,lun,1,b).
asignado(2,ingles,gina,lun,2,b).
asignado(2,ingles,gina,lun,4,b).
asignado(2,ingles,gina,jue,1,b).
asignado(2,ingles,gina,vie,3,b).
asignado(2,infor,jonathan,lun,3,b).
asignado(2,infor,jonathan,mar,1,b).
asignado(2,etica,alisson,jue,1,a).
asignado(2,estsoc,mjose,jue,2,a).
asignado(2,estsoc,mjose,jue,3,a).
asignado(2,estsoc,mjose,jue,3,b).
asignado(2,estsoc,mjose,vie,4,b).
asignado(2,espannol,mjose,lun,1,a).
asignado(2,espannol,mjose,mar,4,a).
asignado(2,espannol,mjose,mie,4,a).
asignado(2,espannol,mjose,vie,3,a).
asignado(2,espannol,mjose,mar,2,b).
asignado(2,espannol,mjose,mie,1,b).
asignado(2,espannol,mjose,vie,1,b).
asignado(2,edfis,mpaula,lun,3,a).
asignado(2,edfis,mpaula,mar,3,b).
asignado(2,ciencias,mjose,lun,2,a).
asignado(2,ciencias,mjose,mie,3,b).
asignado(2,ciencias,mjose,jue,2,b).
asignado(2,ciencias,mjose,jue,4,b).
asignado(2,arte,alisson,mie,3,a).
asignado(1,musica,alonso,mie,1,b).
asignado(1,mate,sol,mar,2,a).
asignado(1,mate,sol,mar,3,a).
asignado(1,mate,sol,mie,1,a).
asignado(1,mate,sol,jue,1,a).
asignado(1,mate,sol,jue,3,a).
asignado(1,mate,sol,jue,4,a).
asignado(1,mate,sol,lun,1,b).
asignado(1,mate,sol,jue,3,b).
asignado(1,ingles,audry,mar,1,a).
asignado(1,ingles,audry,vie,1,a).
asignado(1,ingles,audry,vie,2,a).
asignado(1,ingles,audry,vie,3,a).
asignado(1,ingles,audry,lun,2,b).
asignado(1,ingles,audry,mie,2,b).
asignado(1,ingles,audry,jue,1,b).
asignado(1,ingles,audry,jue,2,b).
asignado(1,ingles,audry,vie,2,b).
asignado(1,ingles,audry,vie,3,b).
asignado(1,infor,jonathan,lun,3,a).
asignado(1,infor,jonathan,vie,4,b).
asignado(1,etica,mjose,mie,4,b).
asignado(1,estsoc,sol,lun,1,a).
asignado(1,estsoc,sol,vie,4,a).
asignado(1,estsoc,sol,lun,3,b).
asignado(1,estsoc,sol,mar,3,b).
asignado(1,espannol,sol,lun,2,a).
asignado(1,espannol,sol,mie,2,a).
asignado(1,espannol,sol,mie,3,a).
asignado(1,espannol,sol,mie,4,a).
asignado(1,espannol,sol,lun,4,b).
asignado(1,espannol,sol,mar,4,b).
asignado(1,espannol,sol,jue,4,b).
asignado(1,edfis,mpaula,mar,4,a).
asignado(1,edfis,mpaula,jue,2,a).
asignado(1,ciencias,sol,lun,4,a).
asignado(1,ciencias,sol,mar,1,b).
asignado(1,ciencias,sol,mar,2,b).
asignado(1,ciencias,sol,mie,3,b).
asignado(1,arte,mjose,vie,1,b).
asignado(trans,resto,alisson,lun,1,a).
asignado(trans,resto,alisson,lun,2,a).
asignado(trans,resto,alisson,lun,4,a).
asignado(trans,resto,alisson,mar,2,a).
asignado(trans,resto,alisson,mar,4,a).
asignado(trans,resto,alisson,mie,2,a).
asignado(trans,resto,alisson,mie,3,a).
asignado(trans,resto,alisson,mie,4,a).
asignado(trans,resto,alisson,jue,2,a).
asignado(trans,resto,alisson,jue,3,a).
asignado(trans,resto,alisson,jue,4,a).
asignado(trans,resto,alisson,vie,1,a).
asignado(trans,resto,alisson,vie,2,a).
asignado(trans,resto,alisson,vie,3,a).
asignado(trans,resto,alisson,vie,4,a).
asignado(trans,resto,alisson,lun,1,b).
asignado(trans,resto,alisson,lun,2,b).
asignado(trans,resto,alisson,lun,3,b).
asignado(trans,resto,alisson,lun,4,b).
asignado(trans,resto,alisson,mar,1,b).
asignado(trans,resto,alisson,mar,2,b).
asignado(trans,resto,alisson,mar,3,b).
asignado(trans,resto,alisson,mar,4,b).
asignado(trans,resto,alisson,mie,1,b).
asignado(trans,resto,alisson,mie,2,b).
asignado(trans,resto,alisson,mie,3,b).
asignado(trans,resto,alisson,mie,4,b).
asignado(trans,resto,alisson,jue,1,b).
asignado(trans,resto,alisson,jue,2,b).
asignado(trans,resto,alisson,jue,3,b).
asignado(trans,resto,alisson,jue,4,b).
asignado(trans,resto,alisson,vie,1,b).
asignado(trans,resto,alisson,vie,2,b).
asignado(trans,resto,alisson,vie,3,b).
asignado(trans,resto,alisson,vie,4,b).
asignado(trans,musica,alonso,mie,1,a).
asignado(trans,ingles,audry,mar,3,a).
asignado(trans,infor,jonathan,lun,3,a).
asignado(trans,edfis,mpaula,mar,1,a).
asignado(trans,edfis,mpaula,jue,1,a).
asignado(inter,resto,alisson,lun,1,a).
asignado(inter,resto,alisson,lun,2,a).
asignado(inter,resto,alisson,lun,3,a).
asignado(inter,resto,alisson,lun,4,a).
asignado(inter,resto,alisson,mar,1,a).
asignado(inter,resto,alisson,mar,2,a).
asignado(inter,resto,alisson,mar,3,a).
asignado(inter,resto,alisson,mar,4,a).
asignado(inter,resto,alisson,mie,1,a).
asignado(inter,resto,alisson,mie,3,a).
asignado(inter,resto,alisson,jue,1,a).
asignado(inter,resto,alisson,jue,2,a).
asignado(inter,resto,alisson,jue,3,a).
asignado(inter,resto,alisson,jue,4,a).
asignado(inter,resto,alisson,vie,1,a).
asignado(inter,resto,alisson,vie,2,a).
asignado(inter,resto,alisson,vie,3,a).
asignado(inter,resto,alisson,vie,4,a).
asignado(inter,resto,alisson,mie,1,b).
asignado(inter,resto,alisson,mie,2,b).
asignado(inter,resto,alisson,mie,3,b).
asignado(inter,resto,alisson,vie,1,b).
asignado(inter,resto,alisson,vie,2,b).
asignado(inter,resto,alisson,vie,3,b).
asignado(inter,resto,alisson,vie,4,b).
asignado(inter,musica,alonso,mie,4,b).
asignado(inter,ingles,mjose,lun,2,b).
asignado(inter,ingles,mjose,lun,3,b).
asignado(inter,ingles,mjose,lun,4,b).
asignado(inter,ingles,mjose,mar,1,b).
asignado(inter,ingles,mjose,mar,2,b).
asignado(inter,ingles,mjose,mar,3,b).
asignado(inter,ingles,mjose,mar,4,b).
asignado(inter,ingles,mjose,jue,1,b).
asignado(inter,ingles,mjose,jue,2,b).
asignado(inter,ingles,mjose,jue,3,b).
asignado(inter,ingles,mjose,jue,4,b).
asignado(inter,infor,jonathan,lun,1,b).
asignado(inter,edfis,mpaula,mie,2,a).
asignado(inter,edfis,mpaula,mie,4,a).
asignado(4,frances,angie,vie,2,a).
asignado(4,frances,angie,mie,3,b).
'SATISFIABLE'.
